name: Load Testing with K6

on: 
  push:
    branches: 
      - 'main'
      - 'master'
  pull_request:
    branches: 
      - 'main'
      - 'master'

jobs:
  load-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  

    - name: Setup Node.js
      uses: actions/setup-node@v4  
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Install K6
      run: |
        wget https://github.com/grafana/k6/releases/download/v0.48.0/k6-v0.48.0-linux-amd64.tar.gz
        tar -xzf k6-v0.48.0-linux-amd64.tar.gz
        sudo cp k6-v0.48.0-linux-amd64/k6 /usr/local/bin/
    
    - name: Start API Server
      run: |
        npm install
        npm start & 
        sleep 5
    
    - name: Run K6 Load Tests
      run: k6 run k6-tests/load.js

    - name: Upload K6 results
      uses: actions/upload-artifact@v4  
      with:
        name: k6-report
        path: k6-report.json